<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Umkm;
use Illuminate\Support\Str;

class UmkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $umkmData = [
            [
                'nama_usaha' => 'Warung Makan Bu Siti',
                'nama_pemilik' => 'Siti Aminah',
                'kategori' => 'Kuliner',
                'deskripsi' => 'Warung makan yang menyajikan masakan rumahan dengan cita rasa khas Jawa. Spesialisasi nasi pecel, soto, dan rawon.',
                'produk_layanan' => 'Nasi Pecel, Soto Ayam, Rawon, Nasi Goreng, berbagai lauk pauk',
                'alamat' => 'Jl. Parangargo Raya No. 15, RT 02/RW 01',
                'telepon' => '081234567890',
                'whatsapp' => '081234567890',
                'tahun_berdiri' => 2015,
                'kisaran_harga_min' => 10000,
                'kisaran_harga_max' => 35000,
            ],
            [
                'nama_usaha' => 'Kerajinan Bambu Makmur',
                'nama_pemilik' => 'Bambang Suryanto',
                'kategori' => 'Kerajinan',
                'deskripsi' => 'Pengrajin bambu yang memproduksi berbagai produk dari bambu seperti anyaman, perabotan, dan dekorasi rumah.',
                'produk_layanan' => 'Keranjang bambu, tikar, lampu hias, furniture bambu, hiasan dinding',
                'alamat' => 'Dusun Utara, RT 05/RW 02',
                'telepon' => '082345678901',
                'whatsapp' => '082345678901',
                'instagram' => '@kerajinanbambumakmur',
                'tahun_berdiri' => 2010,
                'kisaran_harga_min' => 25000,
                'kisaran_harga_max' => 500000,
            ],
            [
                'nama_usaha' => 'Toko Kelontong Sejahtera',
                'nama_pemilik' => 'Ahmad Fauzi',
                'kategori' => 'Perdagangan',
                'deskripsi' => 'Toko kelontong yang menyediakan berbagai kebutuhan sehari-hari lengkap dengan harga terjangkau.',
                'produk_layanan' => 'Sembako, snack, minuman, alat tulis, keperluan rumah tangga',
                'alamat' => 'Jl. Mawar No. 8, RT 03/RW 01',
                'telepon' => '083456789012',
                'whatsapp' => '083456789012',
                'tahun_berdiri' => 2012,
                'kisaran_harga_min' => 1000,
                'kisaran_harga_max' => 200000,
            ],
            [
                'nama_usaha' => 'Jahit Cepat Modern',
                'nama_pemilik' => 'Dewi Lestari',
                'kategori' => 'Jasa',
                'deskripsi' => 'Jasa jahit pakaian, perbaikan baju, dan pembuatan seragam dengan kualitas terbaik.',
                'produk_layanan' => 'Jahit pakaian, reparasi baju, pembuatan seragam, border',
                'alamat' => 'Dusun Tengah, RT 01/RW 03',
                'telepon' => '084567890123',
                'whatsapp' => '084567890123',
                'tahun_berdiri' => 2018,
                'kisaran_harga_min' => 15000,
                'kisaran_harga_max' => 150000,
            ],
            [
                'nama_usaha' => 'Ternak Lele Pak Joko',
                'nama_pemilik' => 'Joko Widodo',
                'kategori' => 'Peternakan',
                'deskripsi' => 'Budidaya ikan lele dengan sistem bioflok. Menyediakan lele konsumsi dan bibit berkualitas.',
                'produk_layanan' => 'Ikan lele konsumsi, bibit lele, pakan lele',
                'alamat' => 'Dusun Selatan, RT 04/RW 02',
                'telepon' => '085678901234',
                'whatsapp' => '085678901234',
                'tahun_berdiri' => 2016,
                'kisaran_harga_min' => 20000,
                'kisaran_harga_max' => 100000,
            ],
            [
                'nama_usaha' => 'Kue Kering Ibu Rini',
                'nama_pemilik' => 'Rini Kusuma',
                'kategori' => 'Kuliner',
                'deskripsi' => 'Produsen kue kering dan kue basah untuk berbagai acara. Menerima pesanan custom sesuai kebutuhan.',
                'produk_layanan' => 'Nastar, kastengel, putri salju, kue basah, snack box',
                'alamat' => 'Jl. Melati No. 12, RT 02/RW 01',
                'telepon' => '086789012345',
                'whatsapp' => '086789012345',
                'instagram' => '@kuekeringiburini',
                'tahun_berdiri' => 2019,
                'kisaran_harga_min' => 35000,
                'kisaran_harga_max' => 200000,
            ],
            [
                'nama_usaha' => 'Bengkel Motor Jaya',
                'nama_pemilik' => 'Andi Pratama',
                'kategori' => 'Jasa',
                'deskripsi' => 'Bengkel motor yang melayani servis rutin, perbaikan, dan modifikasi motor dengan mekanik berpengalaman.',
                'produk_layanan' => 'Servis motor, ganti oli, tune up, perbaikan mesin, spare part',
                'alamat' => 'Jl. Parangargo Raya No. 45, RT 06/RW 03',
                'telepon' => '087890123456',
                'whatsapp' => '087890123456',
                'tahun_berdiri' => 2014,
                'kisaran_harga_min' => 20000,
                'kisaran_harga_max' => 500000,
            ],
            [
                'nama_usaha' => 'Laundry Express',
                'nama_pemilik' => 'Sri Wahyuni',
                'kategori' => 'Jasa',
                'deskripsi' => 'Layanan laundry kiloan dan satuan dengan hasil bersih, wangi, dan rapi. Gratis antar jemput.',
                'produk_layanan' => 'Cuci kering, cuci setrika, setrika saja, dry clean, antar jemput',
                'alamat' => 'Dusun Tengah, RT 03/RW 02',
                'telepon' => '088901234567',
                'whatsapp' => '088901234567',
                'tahun_berdiri' => 2020,
                'kisaran_harga_min' => 5000,
                'kisaran_harga_max' => 50000,
            ],
            [
                'nama_usaha' => 'Sayur Organik Fresh',
                'nama_pemilik' => 'Budi Santoso',
                'kategori' => 'Pertanian',
                'deskripsi' => 'Petani sayuran organik yang menyediakan berbagai sayuran segar tanpa pestimida kimia.',
                'produk_layanan' => 'Kangkung, bayam, sawi, tomat, cabai, terong organik',
                'alamat' => 'Dusun Utara, RT 07/RW 04',
                'telepon' => '089012345678',
                'whatsapp' => '089012345678',
                'instagram' => '@sayurorganikfresh',
                'tahun_berdiri' => 2021,
                'kisaran_harga_min' => 5000,
                'kisaran_harga_max' => 30000,
            ],
            [
                'nama_usaha' => 'Catering Spesial',
                'nama_pemilik' => 'Indah Permata',
                'kategori' => 'Kuliner',
                'deskripsi' => 'Layanan catering untuk acara pernikahan, syukuran, arisan, dan berbagai event dengan menu variatif.',
                'produk_layanan' => 'Nasi kotak, prasmanan, tumpeng, snack, paket acara',
                'alamat' => 'Jl. Anggrek No. 5, RT 01/RW 01',
                'telepon' => '081123456789',
                'whatsapp' => '081123456789',
                'instagram' => '@cateringspesial',
                'facebook' => 'Catering Spesial Parangargo',
                'tahun_berdiri' => 2017,
                'kisaran_harga_min' => 15000,
                'kisaran_harga_max' => 50000,
            ],
            [
                'nama_usaha' => 'Konveksi Mandiri',
                'nama_pemilik' => 'Heru Susanto',
                'kategori' => 'Kerajinan',
                'deskripsi' => 'Jasa pembuatan seragam sekolah, kantor, olahraga, dan kaos custom dengan harga kompetitif.',
                'produk_layanan' => 'Seragam sekolah, seragam kantor, kaos polo, jersey, sablon',
                'alamat' => 'Dusun Selatan, RT 02/RW 03',
                'telepon' => '082234567890',
                'whatsapp' => '082234567890',
                'instagram' => '@konveksimandiri',
                'tahun_berdiri' => 2013,
                'kisaran_harga_min' => 40000,
                'kisaran_harga_max' => 250000,
            ],
            [
                'nama_usaha' => 'Tukang Bangunan Pro',
                'nama_pemilik' => 'Agus Setiawan',
                'kategori' => 'Jasa',
                'deskripsi' => 'Jasa tukang bangunan profesional untuk renovasi rumah, pembangunan baru, dan perbaikan.',
                'produk_layanan' => 'Bangun rumah, renovasi, pasang keramik, cat, plafon',
                'alamat' => 'Dusun Tengah, RT 05/RW 03',
                'telepon' => '083345678901',
                'whatsapp' => '083345678901',
                'tahun_berdiri' => 2011,
                'kisaran_harga_min' => 100000,
                'kisaran_harga_max' => 5000000,
            ],
            [
                'nama_usaha' => 'Es Buah Segar Mbak Rina',
                'nama_pemilik' => 'Rina Wati',
                'kategori' => 'Kuliner',
                'deskripsi' => 'Penjual es buah, es campur, dan minuman segar lainnya dengan buah-buahan pilihan.',
                'produk_layanan' => 'Es buah, es campur, jus buah, es kelapa muda, es teler',
                'alamat' => 'Jl. Parangargo Raya No. 30, RT 04/RW 02',
                'telepon' => '084456789012',
                'whatsapp' => '084456789012',
                'tahun_berdiri' => 2022,
                'kisaran_harga_min' => 8000,
                'kisaran_harga_max' => 25000,
            ],
            [
                'nama_usaha' => 'Fotocopy & Printing Digital',
                'nama_pemilik' => 'Yudi Hermawan',
                'kategori' => 'Jasa',
                'deskripsi' => 'Layanan fotocopy, printing, laminating, jilid, dan percetakan digital dengan hasil berkualitas.',
                'produk_layanan' => 'Fotocopy, print dokumen, cetak foto, laminating, jilid, scan',
                'alamat' => 'Jl. Mawar No. 20, RT 01/RW 01',
                'telepon' => '085567890123',
                'whatsapp' => '085567890123',
                'tahun_berdiri' => 2018,
                'kisaran_harga_min' => 200,
                'kisaran_harga_max' => 50000,
            ],
            [
                'nama_usaha' => 'Bubur Ayam Pagi',
                'nama_pemilik' => 'Sutrisno',
                'kategori' => 'Kuliner',
                'deskripsi' => 'Penjual bubur ayam dengan topping lengkap dan kuah kaldu yang gurih. Buka setiap pagi.',
                'produk_layanan' => 'Bubur ayam, bubur kacang ijo, cakwe, telur asin',
                'alamat' => 'Jl. Melati No. 3, RT 02/RW 01',
                'telepon' => '086678901234',
                'whatsapp' => '086678901234',
                'tahun_berdiri' => 2015,
                'kisaran_harga_min' => 8000,
                'kisaran_harga_max' => 20000,
            ],
        ];

        foreach ($umkmData as $umkm) {
            Umkm::create([
                'nama_usaha' => $umkm['nama_usaha'],
                'slug' => Str::slug($umkm['nama_usaha']),
                'nama_pemilik' => $umkm['nama_pemilik'],
                'kategori' => $umkm['kategori'],
                'deskripsi' => $umkm['deskripsi'],
                'produk_layanan' => $umkm['produk_layanan'],
                'alamat' => $umkm['alamat'],
                'telepon' => $umkm['telepon'],
                'email' => $umkm['email'] ?? null,
                'whatsapp' => $umkm['whatsapp'] ?? null,
                'instagram' => $umkm['instagram'] ?? null,
                'facebook' => $umkm['facebook'] ?? null,
                'website' => $umkm['website'] ?? null,
                'tahun_berdiri' => $umkm['tahun_berdiri'],
                'kisaran_harga_min' => $umkm['kisaran_harga_min'],
                'kisaran_harga_max' => $umkm['kisaran_harga_max'],
                'is_active' => true,
            ]);
        }
    }
}
